fixtures:
  repositories:
    "stdlib": "http://github.com/puppetlabs/puppetlabs-stdlib.git"
    "java": "http://github.com/puppetlabs/puppetlabs-java.git"
  symlinks:
    "aircontrol": "#{source_dir}"

