name         'clue-aircontrol'
version      '0.0.1'
source       'git://github.com/cluetechnologies/clue-aircontrol'
author       'Clue Technologies'
license      'Apache License 2.0'
summary      'Clue Technologies airControl Module'
description  'airControl Module for Puppet'
project_page 'https://github.com/cluetechnologies/clue-aircontrol'
dependency   'puppetlabs/stdlib', '>= 3.0.0'
dependency   'puppetlabs/java', '>= 0.3.0'
